In [12]:
"Utility functions to help deal with tensors"
from fastai.imports.torch import *
from fastai.core import *


In [6]:
def is_listy(x): 
    return isinstance(x,(tuple,list))

In [50]:
#tensor ( x:Any, *rest)-> Tensor
x = 2
rest = (2,4)

if len(rest): x = (x,)+rest
if is_listy(x) and len(x): 
    print(torch.tensor(0))
res = torch.tensor(x) if is_listy(x) else as_tensor(x)
print(torch.tensor(x))
print(as_tensor(x))
  
res.dtype

tensor(0)
tensor([2, 2, 4])
tensor([2, 2, 4])


torch.int64

In [51]:
x

(2, 2, 4)

In [55]:
# np_address (x: np.ndarray)->int
x_nparr = np.array(x); x_nparr
x_nparr.__array_interface__['data'][0]

array([2, 2, 4])

In [113]:
# *****DOESNT WORK YET******
#to_detach (b: Tensors, cpu:True)
bs = [Tensor([2,4]), Tensor(2)];
torch.device = torch.cuda.current_device()
[b.to(torch.device) for b in bs]
def to_detach (b, cpu:True):
    if is_listy(bs): return [to_detach(o, cpu) for o in b]
    if not isinstance(b, Tensor): return b
    b = b.detach()
    return b.cpu() if cpu else b


b = bs[0]

b.to(torch.device)

In [133]:
# to_data(b: ItemList)
x = ItemBase(2)
xs = [ItemBase(i) for i in range(5)]
xss = xs*2
[i.data for i in xs]
def to_data(b):
    if is_listy(b): return [to_data(i) for i in b]
    return b.data if isinstance(b,ItemBase) else b

to_data(xss)

In [152]:
# to_half(bs)

b = [torch.tensor([1.0]),torch.tensor([1.0,2.3, 46.6,  22.])] ;
b = [torch.tensor([1.0]),torch.tensor([1.0,2.3, 46.6,  22.])] ;
b = [torch.tensor([1.0]),torch.tensor([1.0])] ;
b = torch.tensor([1.0,2.3,562])

def to_half(bs):
    if is_listy(bs): return [to_half(b) for b in bs]
    return b.half() if b.dtype!=torch.int64 else b

to_half(b)

tensor([  1.0000,   2.3008, 562.0000], dtype=torch.float16)

In [180]:
# *****DOESNT WORK YET******
#to_device(bs, device)

type(b)

device = None

defaults.device = torch.cuda.device(0)

defaults.device = torch.device('cpu'); defaults.device

#defaults.device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
def to_device(b, device):
    device = ifnone(device, defaults.device)
    print(device)
    if is_listy(b): return [to_device(o, device ) for o in b]
    print(b, device)
    return b.to(device)
    

to_device(b, None)

b.to(torch.device)

torch.Tensor

In [226]:
#data_collate
batch  = [[ItemBase(2)]*2, [64,53,232]]
print(torch.utils.data.dataloader.default_collate(to_data(batch)))
batch  = [ItemBase(2)]*64
print(torch.utils.data.dataloader.default_collate(to_data(batch)))

#??torch.utils.data.dataloader.default_collate

[tensor([ 2, 64]), tensor([ 2, 53])]
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])


In [ ]:
#requires_grad
